spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
mybatis:
   mapperLocations: classpath:/mapper/*.xml
